apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-qbrl
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gvjf-tenant/rhtap-demo-app/hacbs-test-project-qbrl@sha256:516f9b25338274fa00309c106fa18415d879c1d6beeb60ecefbfe743508931ca
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
