apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-qbrl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-qbrl
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-qbrl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-qbrl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-qbrl
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gvjf-tenant/rhtap-demo-app/hacbs-test-project-qbrl@sha256:516f9b25338274fa00309c106fa18415d879c1d6beeb60ecefbfe743508931ca
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
